runtime: nodejs14
entrypoint: npm start
instance_class: B4
manual_scaling:
  instances: 1
handlers:
- url: /_ah/start
  script: node ah_endpoint
  redirect_http_response_code: 302
- url: /
  script: auto
  secure: always
  redirect_http_response_code: 302
