runtime: nodejs14
instance_class: B4
manual_scaling:
  instances: 1
handlers:
- url: /assets
  static_dir: Asset_Files
- url: /client
  static_dir: Client_Files
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
